# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
#       Stop all: docker-compose down
#
version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  app:
    image: thecb4/vapor-blog:1.0
    # build:
    #   context: .
    environment:
      <<: *shared_environment
      DB_USER: "root"
      DB_USER_PASSWORD: "a7dk59rj3-"
      DB_SERVER: "mongo-service"
      DATABASE: "socialbird"
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  # Add 
  mongo_service:
    image: mongo:latest
    container_name: "mongo-service"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: a7dk59rj3-
    ports:
      - '27017:27017'